### PR TITLE
Check building the website with hugo

### LINKED ISSUE #445: Try to build the pages in CI
We can prevent failed builds because of that…

### PR DESCRIPTION
**Pull request by csomh**
Make building with hugo part of the PR checks.

Fixes #445.

Signed-off-by: Hunor Csomortáni <csomh@redhat.com>

### CODE REVIEW

**Comment by csomh** [comment]
recheck

**Review by mfocko — APPROVED** [review]

**Comment by csomh** [comment]
recheck

**Comment by csomh** [comment]
recheck

**Comment by csomh** [comment]
So it seems, Zuul considers merge conditions to be met, if there was previous approval, even if another review was requested by the same user :-|

**Pull request merged**
