### PR TITLE
Fix some broken links

### PR DESCRIPTION
**Pull request by LecrisUT**
Randomly spotted these. Don't suppose `docusaurus` has an equivalent of `linkcheck` builder?

### CODE REVIEW

**Comment by LecrisUT** [comment]
Welp, the CI kinda answered the `linkcheck` issue, but then it's not true after the build is moved: https://packit.dev/docs

**Comment by lachmanfrantisek** [comment]
@LecrisUT , looks like Docusaurus does not like this format. Can we close this? (Or, change the structure to relative paths? (e.g. `./guide`)?

**Review by mfocko — COMMENTED** [review]
It works fine when I open up the web :eyes:

**Comment by LecrisUT** [comment]
Oh, the links are working now. Dunno what happened, but back when I opened this PR, the links would direct to pages like [`docs/docs/guide`](https://packit.dev/docs/docs/guide), seems that has resolved itself :shrug:

**Pull request closed without merging**
