### PR TITLE
Add blog-post for week 43

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
Signed-off-by: Frantisek Lachman <flachman@redhat.com>

### CODE REVIEW

**Review by lbarcziova — COMMENTED** [review]
We should probably mention also [this change](https://github.com/packit/packit/pull/1397). Otherwise, LGTM

**Review by TomasTomecek — APPROVED** [review]
LGTM after the PR which Laura mentioned is added :)

**Comment by lachmanfrantisek** [comment]
PR added, merging...

Thanks for taking a look.

**Comment by TomasTomecek** [comment]
yup, I am getting the same pre-commit exception when trying to merge

**Comment by TomasTomecek** [comment]
regate

**Comment by TomasTomecek** [comment]
recheck

**Pull request merged**
