### PR TITLE
Improve the usability problems in documentation

### PR DESCRIPTION
**Pull request by lbarcziova**
Related to #203

### CODE REVIEW

**Comment by jpopelka** [comment]
@pcahyna could you review this change? Thank you!
I'll give the final thumbs-up once you're happy.

**Review by TomasTomecek — COMMENTED** [review]
pretty good changes!

**Review by TomasTomecek — APPROVED** [review]
LGTM, very nice!

**Comment by pcahyna** [comment]
I am going to review it today if that's enough..

**Comment by TomasTomecek** [comment]
@pcahyna that would be very nice of you!

Since this is the last day of the sprint, I believe we can merge this and address additional comments in subsequent PRs if that's fine with you.

**Comment by lbarcziova** [comment]
I am going to merge this as Tomas wrote, but will be happy about additional comments

**Pull request merged**
