### PR TITLE
Blogposts improvements

### PR DESCRIPTION
**Pull request by FrNecas**
Fixes: #429

### CODE REVIEW

**Comment by FrNecas** [comment]
Navigation after the updates:

screenshot_20220516_145550

**Review by TomasTomecek — APPROVED** [review]
Well, that's exactly what I was asking for :) so LGTM

I know that when we refined this card, folks had comments about the squashing and structure, so let's see what other reviewers will say

**Review by lbarcziova — APPROVED** [review]
:+1:

**Comment by majamassarini** [comment]
I run the Hugo server locally without before looking at this page. 
I should say that I was totally blind and could't find the Weekly Updates at first sight. After I saw your image in the comments here I could finally find them.

If we want the Weekly Updates to be more visible maybe we should raise them one level? Otherwise if we want them not to make too much noise is fine like it is now.

**Comment by FrNecas** [comment]
Renamed Weekly Updates to Weekly Status and moved it to the top as agreed on arch. I am trying to look into RSS in hugo right now

**Comment by FrNecas** [comment]
RSS feed with hugo works out of the box: https://packit.dev/posts/index.xml . With the new structure, also https://packit.dev/posts/weekly/index.xml will work. I am merging this since it was approved and no significant changes were made by the last push (just things we agreed on at arch) :)

**Pull request merged**
