### PR TITLE
Fix the typo on `--resolve-bug` argument

### PR DESCRIPTION
**Pull request by cathay4t**
The correct argument for `pull-from-upstream` is `--resolve-bug`, not
`--resolved-bugs`.

### CODE REVIEW

**Review by lbarcziova — COMMENTED** [review]
Thanks for the contribution! But in the service, it is `--resolved-bugs`, so these occurrences are correct.

**Comment by cathay4t** [comment]
Can we unify them somehow? If I follow the document when using `packit` CLI, I got unknown argument error, I can only get it right by reading code of packit cli.

**Comment by lbarcziova** [comment]
@cathay4t yes, that's a good point, opened packit/packit#2281

**Comment by mfocko** [comment]
Closing as this has been resolved few weeks ago in unifying the args

**Pull request closed without merging**
