### PR TITLE
Hugo Book Theme

### PR DESCRIPTION
**Pull request by jpopelka**
https://themes.gohugo.io/hugo-book

You probably need to do 'git submodule update'.

EDIT: [Alternatives](http://etherpad.corp.redhat.com/IG7CLpjmqO)

### CODE REVIEW

**Review by csomh — COMMENTED** [review]
This is starting to look really nice :smiley:

I have a few notes:
- Is it possible to make the logo bigger? Or that's part of the template?
- Can the left side menu be ordered?
- Can top-level menu items on the left be collapsed?
- Would it be possible to add the main title to the doc pages? For example: to have "Packit Guide" as a title (in the middle column) when opening "Documentation > Packit Guide".

**Comment by TomasTomecek** [comment]
Looks pretty good, I really like the minimalism. I browsed a few pages and all were clear and convenient to read.

If we go for this layout, I'd love to improve the landing page to be more appealing - ideally show some diagram so people are not overwhelmed with lots of text initially. That's out of scope of this PR obviously.

Thanks, Jirko!

**Comment by jpopelka** [comment]
> I'd love to improve the landing page to be more appealing - ideally show some diagram so people are not overwhelmed with lots of text initially.

Yeah, I was thinking about it too. What about (for now, in this PR) just moving [The key principles of packit](https://packit.dev/#the-key-principles-of-packit) and [Why packit?](https://packit.dev/#why-packit) someplace else. Ideas where?

**Comment by jpopelka** [comment]
> * Is it possible to make the logo bigger? Or that's part of the template?

The theme is [customizable](https://github.com/alex-shpak/hugo-book#extra-customisation) so probably, yes, somehow, but it's out of my scope for now.

> * Can the left side menu be ordered?

Fixed

> * Can top-level menu items on the left be collapsed?

Fixed

> * Would it be possible to add the main title to the doc pages?

Fixed. Unlike the previous Learn theme, this Book theme does not use page’s title attribute to create the main heading, so I had to add them manually (it's used only in menu).

**Comment by jpopelka** [comment]
Follow up:
- #216
- #217

**Comment by jpopelka** [comment]
ok, Zuul obviously has a weekend already, merging

**Pull request merged**
