### PR TITLE
Add blog post about Release handling during propose_downstream

### LINKED ISSUE #643: Blogpost about %autorelease
### Description

Please write a blogpost about %autorelease feature we recently finished.

### Benefit

_No response_

### Importance

_No response_

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

### PR DESCRIPTION
**Pull request by nforro**
Fixes #643.

### CODE REVIEW

**Review by csomh — APPROVED** [review]

**Comment by nforro** [comment]
> Maybe just one idea -- what about linking an example Packit config for each use case?

I think the only option that matters here is `sync_changelog`. Maybe I can add something like this to the first scenario:

```md
You most likely want to enable the `sync_changelog` option so that your upstream `%changelog` is synchronized to dist-git as well.
```

And mention `copy_upstream_release_description` and `changelog-entry` in the `%autochangelog` case. What do you think?

**Review by jpopelka — APPROVED** [review]

**Comment by nforro** [comment]
I've added the note about `sync_changelog`. I also wanted to describe how to control changelog when using `%autochangelog`, but I realized there is no way to do so. We have a [request](https://github.com/packit/packit/issues/1887) for an action, but I think enabled `copy_upstream_release_description` should result in release description being embedded into the commit message in case `%autochangelog` is used.

**Review by TomasTomecek — APPROVED** [review]

**Comment by ljavorsk** [comment]
How does `copy_upstream_release_description` work with the upstreams that don't have their project on Github? E.g. https://salsa.debian.org/manpages-l10n-team/manpages-l10n

**Comment by nforro** [comment]
I think that option is GitHub exclusive, but I don't know why, maybe GitLab didn't allow release description in the past. Could you please open an issue?

**Pull request merged**
